# Generated by Django 5.0.7 on 2024-10-15 15:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_enrolledcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courseimg',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='course'),
        ),
    ]
