# Generated by Django 5.0.7 on 2024-10-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontendpart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
